### ISSUE TITLE
Crashes on folder creations

### ISSUE THREAD

**Issue by chevcheli0s** [billziss-gh/sshfs-win#109]
With last beta 3 all OK with folders creation. Except one case when I try to create new folder in dir with no write permissions, then explorer crash. After it restarts new folder appeared. In result I can create folder even I don't have write permissions.

**Comment by billziss-gh** [comment]
This issue is resolved with latest SSHFS-Win and WinFsp.

**Comment by GeniyX** [comment]
I ran into the same problem.
Also, when creating new files, explorer generates an "invalid argument" error and the file is not visible (as if it had not been created). However, after updating the folder, it contains two new files instead of one.

If accessed via cmd, then when I try to execute commands to create a directory or file, get error "Access is denied.". Although in fact, files and directories are successfully created.

When working through cygwin, such errors do not occur.

Duplication of new files occurs only when using explorer.

Used versions: sshfs-win-3.5.20024 and winfsp-1.6.20027.
I connect using SiriKali-1.4.2.
