### ISSUE TITLE
map to root (or other directory) instead of home

### ISSUE THREAD

**Issue by KrullBorg** [billziss-gh/sshfs-win#12]
is there a way to map the drive to the root directory (or something else) instead of the home directory of the user logged in?

**Comment by billziss-gh** [comment]
Apologies for the very late response. I have just returned from vacation.

What you want might be possible if you use the sshfs command from a Cygwin prompt. Something along the lines of:

```
$ sshfs user@host:/ X:
```

**Comment by KrullBorg** [comment]
ok thanks

**Comment by scot5** [comment]
I noticed you can also change the mount map like this:
\\sshfs\user@host\path\relative\to\home\directory
So if you want the root directory you'd get something like
\\sshfs\user@host\..\..

**Comment by dredkin** [comment]
This should be added to Readme! I've already uninstalled sshfs-win, and got here only to file an issue, and found this wonderful workaround.
So I had to install sshfs-win again :)

**Comment by xc** [comment]
Indeed it should be in readme by default. PS. any plan to support absolute path? eg. \\sshfs\user@host\\var\test . , will be very helpful.

PS. sshfs-win is much faster than winSshFS in my setup(internet mount)!

**Comment by billziss-gh** [comment]
I have added some information on the README. Please let me know if this works for you.

>It is also possible to map the remote root directory by starting the path with a double backslash as in the following example:
>
>     \\sshfs\billz@linux-host\\home\billz

**Comment by aubade** [comment]
This doesn't work for me, unfortunately. I get a remote permissions denied error if I send any double-backslashed path (But the home folder does work)

**Comment by DutchKillerbee** [comment]
"Root maping" doesn't work for either. Relative path works.
GO: `\\sshfs\user@host\..\..\tmp`
NOGO:`\\sshfs\user@host\\tmp`

**Comment by tdobes** [comment]
You can kinda-sorta get this to work by using an absurd number of backslashes.  However, this then exposes other problems for mounts of subdirectories.

I'm testing with a Linux host, Windows 7 64-bit, sshfs-win-2.7.17334-x64.msi, and winfsp-1.2.17346.msi.  As a sanity check, I also tested using another Linux system (same network as the Windows system).

Works on Linux:
$ mkdir mnt && sshfs -p 2222 myuser@linuxhost:/ mnt
(mounts root of linuxhost as expected)

Fails on Windows:
> net use z: \\sshfs\myuser@linuxhost!2222\\
(mounts home directory on z:)
> net use z: \\sshfs\myuser@linuxhost!2222\\\
(System error 67 has occurred.  The network name cannot be found.)
> net use z: \\sshfs\myuser@linuxhost!2222\
(System error 67 has occurred.  The network name cannot be found.)

Works on Windows:
> net use z: \\sshfs\myuser@linuxhost!2222\\\\
(mount root of linuxhost on Z:)


However, my ultimate goal was to mount /mnt/usb on Z:
Things fell apart on the Windows side when I wanted to do a subdirectory.  I appear to be encountering some sort of bug in sshfs-win or WinFsp which ties up drive letters and prevents me from releasing them.

This works on the Linux client:
$ mkdir usb && sshfs -p 2222 myuser@linuxhost:/mnt/usb usb
(mounts /mnt/usb of linuxhost as expected)

Fails on Windows:
> net use z: \\sshfs\myuser@linuxhost!2222\\\\mnt\\usb
(System error 67 has occurred.  The network name cannot be found.)
...then Z: shows up as "already in use" on future "net use" commands.  "net use z: /d" or clicking "Disconnect" in the explorer GUI does not work either, reporting that the connection does not exist.

...maybe the problem is with the double-backslash between mnt and usb.  Let's just try to do mnt.
> net use y: \\sshfs\myuser@linuxhost!2222\\\\mnt
(System error 67 has occurred.  The network name cannot be found.)
...then Y: shows up as "already in use" on future "net use" commands.  "net use y: /d" or clicking "Disconnect" in the explorer GUI does not work either, reporting that the connection does not exist.

I ended up hacking around the problem by creating a dummy user on the Linux side (same uid/gid as my normal user) with the directory I wanted to mount set as its home directory.

**Comment by camAtGitHub** [comment]
@tdobes I found during my exploration of sshfs-win, that if doing something like:

` net use y: \\sshfs\myuser@linuxhost\\\` eg. trying to mount '/' that the command worked, but y: is inaccessible if you do a net use to show the mounts it shows: 

```
Status       Local     Remote                    Network
-------------------------------------------------------------------------------
             Z:        \\sshfs\myuser@linuxhost\\
```
But you have to input the original mount to delete it:
`net use  \\sshfs\myuser@linuxhost\\\ /del`   (note the triple slash)

**Comment by sganis** [comment]
I am reporting in this issue as I think is related.

Testing WinFsp 2018.2 B1 v1.4B2 and SSHFS-Win 3.2 BETA v3.2.18213 on Windows 7. 
It is hard to disconnect the drive from windows explorer, it does not disconnect. 
I have to kill the sshfs process run by SYSTEM, then the drive stays in error status. The only way to remove it is to mount with the command line and kill the process in the terminal with Control+C.

When mounting using `> net use Z: \\sshfs\user@host` it requires two commands to unmount:
`> net use Z: /del` 
and 
`> net use `\\sshfs\user@host /del`
in any order. 
I also noticed that the remote path must be the original path that was used to mount, stored in the registry HKCU\Network, not the path reported by the `> net use` command.

**Comment by kml27** [comment]
I think @sganis issue may be a separate one. 
Using winfsp-1.3.18160 and sshfs-win-2.7.17334-x64
 I see a similar symptom when editing files on a drive mount from a vm using \\sshfs\user@localhost!2222. Sometimes the connection just goes down and I cannot disconnect from the Windows UI, but a net use Z: /del seems to usually work. Sometimes the drive is not removed from explorer (I will try deleting the sshfs UNC path next time too). I have only had the time and opportunity to gather minimal info (WER and a screenshot of the i/o error dialog) on the issue. I'll add them when to a new (or related) issue when I have more time if it appears to be a sshfs-win or winfsp issue.

**Comment by sganis** [comment]
I am using this batch script to unmount:
```
:: Unmount drive
:: 08/01/2018, sganis
@echo off
if [%1]==[] goto :usage
set DRIVE=%1
echo unmounting %DRIVE%...
set LETTER=%DRIVE:~0,-1%
for /f "tokens=3" %%e in ('reg query HKCU\Network\%LETTER% /v RemotePath') do (
	net use %%e /del
	net use %DRIVE% /del
)
goto :eof
:usage
echo usage: %0 ^<drive^>
exit /B 1
```

**Comment by asimoneo** [comment]
So, replying to all of previous guys here, the solution for windows is quite easy:
`net use z: \\sshfs\user@host!port\..\..\hdd `
**This mounts /hdd folder, works for ordinary user, that has a home directory at /home/user**
If you are mounting as root, use net use z: \\sshfs\user@host!port\..\hdd (because home directory for root user is /root, so only one \..\ needed to go to root of the filesystem)
this worked for me after 5-8 hours of tickling around with windows. I hope that helps. 
P.s. to the author - you should write a tiny gui for mounting, because the software you made is obviously golden and blazing fast, but that bullshit syntax and crazy complicated mounting kills everything. The software is actually useful not only to programmers, but for actual users who are maintaining a small server for backups and file storage.

**Comment by billziss-gh** [comment]
@asimoneo take a look at [SiriKali](https://github.com/mhogomchungu/sirikali/releases/tag/1.3.5).

**Comment by asimoneo** [comment]
@billziss-gh yep I did try it, but the interface is counter-intuitive and there is no obvious way to keep drives mounted. Plus sshfs drives were mounted as local drives, but not network ones, which can lead to some excessive traffic due caching, etc. So I've abandoned this option. But thanks for a guess.

**Comment by billziss-gh** [comment]
This has finally been implemented. Use the syntax `\\sshfs.r\user@host\path` to map a drive to `/path` on the SSHFS host.

**Comment by fakkoweb** [comment]
Hello there!

I can correctly connect to it:
![image](https://user-images.githubusercontent.com/4292783/74109125-1269a800-4b81-11ea-908f-61f0c3303974.png)
although as you can see my machine has no \home directory, since this is an old debian machine with root access, but running OpenSSH_7.5p1. Unless I have to allow anything on that, I don't know. It is behind a router, but I port-forwarded the TCP port only correctly.

I tried every possible combination of the UNC proposed above to map it as a drive on Windows 10. I tried "\" or "." or "\..\.." or nothing. I tried with sshfs and sshfs.r

What i get is a "access is denied." and I have no insight on the error. I tried also from command line (both net use or sshfs-win), but nothing.
The fact that I can connect with Putty makes me thing it is a path issue...

I am using:
https://github.com/billziss-gh/sshfs-win/tree/v3.5.20024
winfsp-1.6.20027 (latest release)

**Comment by DemonBlueFox** [comment]
Hello I just came across this conversation after some research on sshfs.r and I wanted to know why with this command the path of the system disks is displayed with a small dot after the letter of the disks not readable by the console ?

**Comment by CaptainXLAB** [comment]
> Hello I just came across this conversation after some research on sshfs.r and I wanted to know why with this command the path of the system disks is displayed with a small dot after the letter of the disks not readable by the console ?

Yes. I'm here at 3am with no sleep exactly because of that dot.

I'm unable to "map network drive" with Windows because in root, each drive has it's own letter (like C: D: E: F:) and windows filesystem doesn't allow ":" so it replaces that with "" (looks like a strange dot in explorer but looks like a missing emote box anywhere I try to paste it)

A workaround for this would be to use NTFS junctions to create junctions for all existing drives into C:\ so that it can be mounted through there. Any way to do this directly though?

**Comment by carlox97** [comment]
> > Hello I just came across this conversation after some research on sshfs.r and I wanted to know why with this command the path of the system disks is displayed with a small dot after the letter of the disks not readable by the console ?
> 
> Yes. I'm here at 3am with no sleep exactly because of that dot.
> 
> I'm unable to "map network drive" with Windows because in root, each drive has it's own letter (like C: D: E: F:) and windows filesystem doesn't allow ":" so it replaces that with "" (looks like a strange dot in explorer but looks like a missing emote box anywhere I try to paste it)
> 
> A workaround for this would be to use NTFS junctions to create junctions for all existing drives into C:\ so that it can be mounted through there. Any way to do this directly though?

![Screenshot 2023-06-08 195522](https://github.com/winfsp/sshfs-win/assets/31673755/674368d6-70a3-4896-a97e-54eeee7ec70f)


I have the same issue with map network drive. Have you found a solution?
@billziss-gh

**Comment by juangburgos** [comment]
Another solution to mount a drive different than C, is to define the SFTP server's default directory to the drive of interest. For example, to mount F, in `/etc/ssh/sshd_config` set:
```bash
Subsystem	sftp	/usr/lib/ssh/sftp-server -d "/f"
```

**Comment by POD-SYS** [comment]
> Another solution to mount a drive different than C, is to define the SFTP server's default directory to the drive of interest. For example, to mount F, in `/etc/ssh/sshd_config` set:
> 
> Subsystem	sftp	/usr/lib/ssh/sftp-server -d "/f"

How do I map a folder in another drive on the client side, as I want it to be for specific user?
I'm using SSHFS on Windows client and server. So far I've managed to map the user folder or root (with` \..\..`) but I can't figure out how to move to another drive (I'm not so familiar with Linux).

**Comment by Skipperio** [comment]
For anyone searching to mount folder other than /home

`net use X: \\sshfs.r\%username%@%host_IP%\\path\to\any\folder`

**Comment by POD-SYS** [comment]
> For anyone searching to mount folder other than /home
> 
> `net use X: \\sshfs.r\%username%@%host_IP%\\path\to\any\folder`

This will map any sub-directory inside the user's home directory, not a directory in ANOTHER drive on the host.
I've managed to do this with a sym-link, pointing to another drive, but downloading files through this sym-link was possible only if the user was permitted to root.

**Comment by Skipperio** [comment]
> > For anyone searching to mount folder other than /home
> > `net use X: \\sshfs.r\%username%@%host_IP%\\path\to\any\folder`
> 
> This will map any sub-directory inside the user's home directory, not a directory in ANOTHER drive on the host. I've managed to do this with a sym-link, pointing to another drive, but downloading files through this sym-link was possible only if the user was permitted to root.

Well as long as directory has permissions. it doesn't matter where it is. If it's drive or not.
