### ISSUE TITLE
Question: About version of sshfs

### ISSUE THREAD

**Issue by DutchKillerbee** [billziss-gh/sshfs-win#23]
Hello
Is there any particular reason why you are still at version a9a1cc0 (1 Mar 2016) for sshfs?
A lot has changed since may 2016.
Thanks 
KB

**Comment by billziss-gh** [comment]
The main reason is that SSHFS has changed its build system to meson+ninja, which I am unfamiliar with and unclear whether they exist on Cygwin (they did not some time ago when I checked).

If upstream SSHFS has acquired important features that should be in SSHFS-Win, I would be happy to accept a PR that brings SSHFS-Win to a more recent version of SSHFS.

**Comment by 4O4** [comment]
I'm picking this up, I'll submit a PR if everything works correctly. Besides build system change, there appear to be some major incompatibilities in the code. 

For instance I don't see `sshfs.mnt_mode` anywhere anymore.  I'm guessing that it was an important permissions-related patch and needs to be reimplemented somewhere in the new codebase. @billziss-gh I would be grateful if you could share some insights on this, otherwise I'll just dig into sshfs code to understand how it worked before and how it works now.

**Comment by 4O4** [comment]
Okay, nevermind. I've just seen that you're already working on this in https://github.com/billziss-gh/sshfs/ 😄

**Comment by billziss-gh** [comment]
@404 yes.

I am about to release WinFsp v1.4B2 with FUSE3 support. I have already ported the latest version of SSHFS to Cygwin again and will submit a PR for this to the upstream SSHFS project. Then we should be able to bring SSHFS-Win to the latest version of SSHFS.

**Comment by billziss-gh** [comment]
Closing this as it is now merged into master. I will make beta releases available soon.

**Comment by billziss-gh** [comment]
The beta release is now available:

https://github.com/billziss-gh/sshfs-win/releases/tag/v3.2.18213
