### ISSUE TITLE
Is there a way to install SSHFS as regular user?

### ISSUE THREAD

**Issue by Alestrix** [billziss-gh/sshfs-win#251]
Title says it all and I cannot find anything about this here.
I guess the question separates into two questions:

- Is there a non-msi installer, or an msi installer that lets me chose to install the files into a directory writable by a regular user without elevated privileges?
- Can a sshfs-backed drive be created in windows without having elevated privileges?

What I am trying to do: I need to transfer data from a remote host accessible only via RDP onto an SFTP Server that is only accessible from the host running the RDP client. I can pass drives through to the RDP server so I thought sshfs might be a solution. Temporarily storing the data locally and then SFTPing them further is of course a solution, but it takes twice the time.

**Comment by billziss-gh** [comment]
The SSHFS MSI currently requires administrative privileges. However it could be modified to be installed without them.

The bigger problem is that SSHFS requires WinFsp, which requires administrative privileges to be installed, because it includes a kernel driver. So in the end you would need administrative privileges to install SSHFS, unless someone else installed WinFsp for you.

**Comment by Alestrix** [comment]
Thanks @billziss-gh, so the answer is no unfortunately.
