### ISSUE TITLE
not able to access root directory when mounting and symlinks are not working

### ISSUE THREAD

**Issue by shivsoji** [billziss-gh/sshfs-win#4]
not able to access symlinks and unable to go to root directory

**Comment by billziss-gh** [comment]
I will need more information on this.

However absolute symlinks are not followed by default. They now need the `-o rellinks` option which unfortunately SSHFS-Win has not been updated to use yet. [My focus has been on finishing off WinFsp in the last couple of months.]

Please give me some additional information re: root directory issue as I do not understand what you mean.

**Comment by shivsoji** [comment]
when i do  `\\sshfs\user@host `, it opens home directory of that user but i want to access /var/www. how can i do?

**Comment by billziss-gh** [comment]
This is up to how the sshd daemon is set up on the server and has nothing to do with sshfs which runs on the client side. You would likely have to login as root, which many sshd daemons do not allow.

I would recommend reading up on sshd and how to configure it to do what you want.

**Comment by shivsoji** [comment]
ok, thanks

**Comment by jdmansour** [comment]
I had the same issue, and it is not due to a restrictive setting of sshd. When you log in via ssh, the server puts you into your home directory (e.g. `/home/jason`), but you can still access files outside of it (if you have the correct permissions).

Dokan sshfs allows you to specify an absolute remote path, e.g. `/` or `/some/folder`, but sshfs-win only allows folders relative to your home directory. What you can do, however, is to go up (again, if you have access rights to those directories on the server). So the following does work:

    \\sshfs\user@host.com\..\..

**Comment by shivsoji** [comment]
thanks i will try
