### ISSUE TITLE
Security issue: Credentials stored in plain text format

### ISSUE THREAD

**Issue by embeh** [billziss-gh/sshfs-win#443]
This is using winfsp-2.0.23075 and sshfs-win-3.5.20357-x64 on Windows 10 Enterprise 22H2

When connecting to a server by entering '\\sshfs\USER@servername" into Windows Explorer, there is an option called 'Remember me' to store the credentials in the Windows Credential manager. After using this option it is not difficult to read the stored password in plain text from the credential store. I can provide instructions on how to do this on request.

Any chance to encrypt the password with the user's Windows credentials?

**Comment by billziss-gh** [comment]
The Windows Credential Manager (WCM) is the default service that the Windows OS provides for the purpose of "securely" storing credentials. The credentials stored in it are encrypted (and not plain text) and many Windows applications use the WCM to store credentials (e.g. Outlook, git).

It is true that if you have access to the account you can read credentials from the credential store without additional obstacles. This is by design as the WCM security boundary is the user account and any process that runs within the account is able to access the account's credentials in the manager.

Now you may not think this is very secure and I might even be inclined to agree with you. There is a tradeoff between convenience and security and the Windows designers erred on the side of convenience and chose that you have immediate access to all your credentials once you are logged in. Contrast this with something like KeepassX where you may have to reenter a master password every time you want to use a credential; more security but less convenience.

**Comment by embeh** [comment]
Thanks for the comments. 

Other open-source software using the same mechanism (e.g. Nextcloud) do not store the plaintext password in the credential manager but an encrypted version (they seem to use [qtkeychain](https://github.com/frankosterfeld/qtkeychain)). Not sure how this exactly works but there seems to be a Windows mechanism that allows you to hash a password using the current Windows user credentials and the local machine key. 

I just found it a bit scary to see my ssh password in the clear using a few PowerShell commands. Any script on my machine could do the same...

But if this is 'as designed' then please feel free to close this issue.

**Comment by billziss-gh** [comment]
Suppose that sshfs-win was to encrypt passwords prior to storing them in the WCM. What key would it use for this purpose?

- If it used a static key, an attacker could simply read it from this repo.
- If it used a dynamic key, that key would still have to be tied to a particular account on the machine. So if the sshfs-win processes can read that key and use it to decrypt your credentials, then so can any other process that runs under the same account.

As long as we want to use the standard Windows secure store we are constrained by its design. There are alternative secure store systems (e.g. Keychain on the Mac) which allow access to a specific process, but unfortunately this is not the case with WCM (AFAIK).

<img width="646" alt="Screenshot 2024-09-18 at 16 46 57" src="https://github.com/user-attachments/assets/8970a51b-7c7f-4e01-a843-44c5c4dd4493">
